spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo_wallet?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
server:
  port: 9000

#mybatis:
#  type-aliases-package: com.hrxcy.pojo
##  在这里翻一次车，艹。
#  mapper-locations: classpath:mapper/*.xml
#
mybatis-plus:
  type-aliases-package: xyz.hrxcy.pojo
  mapper-locations: classpath:mapper/*.xml